#!/usr/bin/env bash
# Zordle practice slot deploy orchestrator.
#
# Required env vars:
#   SLOT_ACCOUNT_ADDRESS       Account that pays for migration + dictionary load.
#   SLOT_PRIVATE_KEY           Matching private key.
#
# Optional:
#   SLOT_NAME                  Cartridge slot name. Defaults to zordle-practice-slot.
#   RPC_URL                    Override slot RPC.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PROFILE="slot"
SLOT_NAME="${SLOT_NAME:-zordle-practice-slot}"
RPC_URL="${RPC_URL:-https://api.cartridge.gg/x/${SLOT_NAME}/katana}"
MANIFEST="$ROOT/manifest_slot.json"
DOJO_CONFIG="$ROOT/dojo_slot.toml"
CLIENT_ENV="$ROOT/client/.env.slot"
SEPOLIA_ENV="$ROOT/client/.env.sepolia"
DOJO_CONFIG_BAK="$ROOT/.dojo_slot.toml.bak.$$"

restore_dojo_config() {
  if [[ -f "$DOJO_CONFIG_BAK" ]]; then
    mv "$DOJO_CONFIG_BAK" "$DOJO_CONFIG"
  fi
}
trap restore_dojo_config EXIT

info() { echo "[slot] $1"; }
fail() { echo "[slot] $1" >&2; }

if [[ -z "${SLOT_ACCOUNT_ADDRESS:-}" || -z "${SLOT_PRIVATE_KEY:-}" ]]; then
  fail "SLOT_ACCOUNT_ADDRESS and SLOT_PRIVATE_KEY must be set."
  exit 1
fi

for dep in sozo jq node; do
  if ! command -v "$dep" >/dev/null 2>&1; then
    fail "Required tool not found: $dep"
    exit 1
  fi
done

cp "$DOJO_CONFIG" "$DOJO_CONFIG_BAK"
SLOT_ACCOUNT_ADDRESS="$SLOT_ACCOUNT_ADDRESS" RPC_URL="$RPC_URL" perl -0pi -e \
  's#(rpc_url\s*=\s*)"[^\"]+"#$1"$ENV{RPC_URL}"#s;
   s/("zordle_0_1-actions"\s*=\s*\[\s*)"[^\"]+"/$1"$ENV{SLOT_ACCOUNT_ADDRESS}"/s;
   s/("zordle_0_1-setup"\s*=\s*\[\s*)"[^\"]+"/$1"$ENV{SLOT_ACCOUNT_ADDRESS}"/s' \
  "$DOJO_CONFIG"

info "Building profile $PROFILE"
sozo build -P "$PROFILE"

info "Migrating to $RPC_URL"
sozo migrate -P "$PROFILE" \
  --rpc-url "$RPC_URL" \
  --account-address "$SLOT_ACCOUNT_ADDRESS" \
  --private-key "$SLOT_PRIVATE_KEY"

if [[ ! -f "$MANIFEST" ]]; then
  fail "$MANIFEST not generated by sozo migrate."
  exit 1
fi

WORLD=$(jq -r '.world.address' "$MANIFEST")
ACTIONS=$(jq -r '.contracts[] | select(.tag == "zordle_0_1-actions") | .address' "$MANIFEST")
SETUP=$(jq -r '.contracts[] | select(.tag == "zordle_0_1-setup") | .address' "$MANIFEST")

if [[ -z "$WORLD" || -z "$ACTIONS" || -z "$SETUP" ]]; then
  fail "Failed to extract addresses from $MANIFEST"
  exit 1
fi

cat > "$CLIENT_ENV" <<EOF
# Generated by scripts/deploy_slot.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VITE_PUBLIC_NAMESPACE_PRACTICE=zordle_0_1
VITE_PUBLIC_SLOT_PRACTICE=$SLOT_NAME
VITE_PUBLIC_NODE_URL_PRACTICE=$RPC_URL
VITE_PUBLIC_CHAIN_ID_PRACTICE=WP_ZORDLE_PRACTICE_SLOT
VITE_PUBLIC_WORLD_ADDRESS_PRACTICE=$WORLD
VITE_PUBLIC_ACTIONS_ADDRESS_PRACTICE=$ACTIONS
VITE_PUBLIC_VRF_ADDRESS_PRACTICE=0x0
EOF

# Merge the practice block into .env.sepolia so `pnpm sepolia` loads both NFT
# and practice env vars from a single mode file. Idempotent via marker block.
PRACTICE_BLOCK_BEGIN="# --- practice slot (begin) ---"
PRACTICE_BLOCK_END="# --- practice slot (end) ---"

if [[ -f "$SEPOLIA_ENV" ]]; then
  perl -i -0pe "s/\Q${PRACTICE_BLOCK_BEGIN}\E.*?\Q${PRACTICE_BLOCK_END}\E\n?//s" "$SEPOLIA_ENV"
fi

cat >> "$SEPOLIA_ENV" <<EOF
${PRACTICE_BLOCK_BEGIN}
# Generated by scripts/deploy_slot.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VITE_PUBLIC_NAMESPACE_PRACTICE=zordle_0_1
VITE_PUBLIC_SLOT_PRACTICE=$SLOT_NAME
VITE_PUBLIC_NODE_URL_PRACTICE=$RPC_URL
VITE_PUBLIC_CHAIN_ID_PRACTICE=WP_ZORDLE_PRACTICE_SLOT
VITE_PUBLIC_WORLD_ADDRESS_PRACTICE=$WORLD
VITE_PUBLIC_ACTIONS_ADDRESS_PRACTICE=$ACTIONS
VITE_PUBLIC_VRF_ADDRESS_PRACTICE=0x0
${PRACTICE_BLOCK_END}
EOF
info "Merged practice block into $SEPOLIA_ENV"

# Skip the dictionary load on incremental redeploys — the setup contract
# rejects re-loading via dict.assert_not_loaded(), and the prior load
# survives the actions-class upgrade. Read the dictionary view's `loaded`
# flag (last felt of the returned struct) to decide.
is_dict_loaded() {
  local out last
  out=$(sozo call -P "$PROFILE" --rpc-url "$RPC_URL" "$ACTIONS" get_dictionary 2>/dev/null) || return 1
  last=$(echo "$out" | tr -d '[]' | awk '{ print $NF }' | sed 's/^0x0x/0x/')
  [[ "$last" =~ ^0x0*1$ ]]
}

if is_dict_loaded; then
  info "Dictionary already loaded — skipping load step"
else
  if [[ ! -d "$ROOT/scripts/node_modules" ]]; then
    info "Installing scripts deps"
    (cd "$ROOT/scripts" && pnpm install --silent)
  fi

  info "Loading dictionary"
  NODE_URL="$RPC_URL" \
  ACCOUNT_ADDRESS="$SLOT_ACCOUNT_ADDRESS" \
  PRIVATE_KEY="$SLOT_PRIVATE_KEY" \
  SETUP_ADDRESS="$SETUP" \
    node "$ROOT/scripts/load_dictionary.mjs"
fi

info "Slot deploy complete"
echo "World:   $WORLD"
echo "Actions: $ACTIONS"
echo "Setup:   $SETUP"
echo "Client env: $CLIENT_ENV"
