#!/usr/bin/env bash
# Zordle — Sepolia deploy orchestrator.
#
# Required env vars:
#   DEPLOYER_ADDRESS       Sepolia account that pays for the migration + dict load.
#                          Must be funded with STRK (or ETH if your account uses v2 fees).
#   DEPLOYER_PRIVATE_KEY   The matching key. Don't commit it.
#
# Optional:
#   RPC_URL                Override the Sepolia RPC. Defaults to Cartridge's managed
#                          endpoint (free, no key, decent SLA): https://api.cartridge.gg/x/starknet/sepolia
#
# Side effects:
#   - writes manifest_sepolia.json at the repo root
#   - writes client/.env.sepolia with the deployed addresses
#   - writes client/public/words.txt as part of the dictionary load
#
# Idempotency:
#   - sozo migrate is incremental: re-running with the same dojo_sepolia.toml +
#     funded account is safe.
#   - load_dictionary.mjs is NOT incremental beyond a per-batch granularity. If
#     the load fails partway through, see the note in scripts/load_dictionary.mjs
#     about adjusting start_pack_id to resume.
#
# Usage:
#   DEPLOYER_ADDRESS=0x... DEPLOYER_PRIVATE_KEY=0x... bash scripts/deploy_sepolia.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PROFILE="sepolia"
MANIFEST="$ROOT/manifest_sepolia.json"
DOJO_CONFIG="$ROOT/dojo_sepolia.toml"
CLIENT_ENV="$ROOT/client/.env.sepolia"
DEFAULT_RPC="https://api.cartridge.gg/x/starknet/sepolia"

# --- ANSI helpers --------------------------------------------------------
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
info()  { echo -e "${GREEN}[deploy]${NC} $1"; }
warn()  { echo -e "${YELLOW}[deploy]${NC} $1"; }
fail()  { echo -e "${RED}[deploy]${NC} $1" >&2; }

# --- 0. Validate environment --------------------------------------------

if [[ ! -f "$DOJO_CONFIG" ]]; then
  fail "Missing $DOJO_CONFIG. Did this clone include the Sepolia profile?"
  exit 1
fi

if [[ -z "${DEPLOYER_ADDRESS:-}" || -z "${DEPLOYER_PRIVATE_KEY:-}" ]]; then
  fail "DEPLOYER_ADDRESS and DEPLOYER_PRIVATE_KEY must be set in your env."
  echo "  example:"
  echo "    DEPLOYER_ADDRESS=0x... DEPLOYER_PRIVATE_KEY=0x... bash scripts/deploy_sepolia.sh"
  exit 1
fi

RPC_URL="${RPC_URL:-$DEFAULT_RPC}"

for dep in sozo jq node; do
  if ! command -v "$dep" >/dev/null 2>&1; then
    fail "Required tool not found: $dep"
    exit 1
  fi
done

info "Profile:  $PROFILE"
info "RPC:      $RPC_URL"
info "Account:  $DEPLOYER_ADDRESS"
echo "============================================"

# --- 1. Build ------------------------------------------------------------

info "Step 1/4 — sozo build -P $PROFILE"
sozo build -P "$PROFILE"

# --- 2. Migrate (with retry — Sepolia is sometimes flaky) ----------------

info "Step 2/4 — sozo migrate -P $PROFILE"
ATTEMPT=0
MAX_ATTEMPTS=5
BACKOFF=60

migrate_once() {
  sozo migrate -P "$PROFILE" \
    --rpc-url "$RPC_URL" \
    --account-address "$DEPLOYER_ADDRESS" \
    --private-key "$DEPLOYER_PRIVATE_KEY"
}

until migrate_once; do
  ATTEMPT=$((ATTEMPT + 1))
  if (( ATTEMPT >= MAX_ATTEMPTS )); then
    fail "migrate failed after $MAX_ATTEMPTS attempts."
    exit 1
  fi
  warn "migrate attempt $ATTEMPT failed; retrying in ${BACKOFF}s…"
  sleep "$BACKOFF"
  BACKOFF=$((BACKOFF * 2))
done

# --- 3. Pull addresses out of the freshly-written manifest ---------------

if [[ ! -f "$MANIFEST" ]]; then
  fail "$MANIFEST not generated by sozo migrate. Aborting."
  exit 1
fi

WORLD=$(jq -r '.world.address' "$MANIFEST")
ACTIONS=$(jq -r '.contracts[] | select(.tag == "zordle_0_1-actions") | .address' "$MANIFEST")
SETUP=$(jq -r '.contracts[] | select(.tag == "zordle_0_1-setup") | .address' "$MANIFEST")

if [[ -z "$WORLD" || -z "$ACTIONS" || -z "$SETUP" ]]; then
  fail "Failed to extract one or more addresses from $MANIFEST"
  echo "  WORLD=$WORLD ACTIONS=$ACTIONS SETUP=$SETUP"
  exit 1
fi

info "World:    $WORLD"
info "Actions:  $ACTIONS"
info "Setup:    $SETUP"

# --- 4. Write client env + run dictionary loader -------------------------

info "Step 3/4 — writing $CLIENT_ENV"
cat > "$CLIENT_ENV" <<EOF
# Generated by scripts/deploy_sepolia.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Each player connects with their own Cartridge Controller account; the
# deployer's credentials never reach the client. This file is committed
# so contributors can run the client against the live world.
VITE_PUBLIC_NODE_URL=$RPC_URL
VITE_PUBLIC_NAMESPACE=zordle_0_1
VITE_PUBLIC_SLOT=zordle-sepolia
VITE_PUBLIC_WORLD_ADDRESS=$WORLD
VITE_PUBLIC_ACTIONS_ADDRESS=$ACTIONS
VITE_PUBLIC_DENSHOKAN_ADDRESS=0x0004e6e5bbf18424dfb825f1dbb65e10473b4603a1ec7b9ab02c143d877114f9
VITE_PUBLIC_VRF_ADDRESS=0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f
EOF

if [[ ! -d "$ROOT/scripts/node_modules" ]]; then
  info "Installing scripts deps…"
  (cd "$ROOT/scripts" && pnpm install --silent)
fi

info "Step 4/4 — loading dictionary onto Sepolia (this can take 15-30 minutes)"
warn "On Sepolia each tx confirmation is ~30s vs ~1s on katana."
NODE_URL="$RPC_URL" \
ACCOUNT_ADDRESS="$DEPLOYER_ADDRESS" \
PRIVATE_KEY="$DEPLOYER_PRIVATE_KEY" \
SETUP_ADDRESS="$SETUP" \
  node "$ROOT/scripts/load_dictionary.mjs"

# --- 5. Summary ----------------------------------------------------------

echo ""
echo "============================================"
info "Sepolia deploy complete."
echo ""
echo "  World:    $WORLD"
echo "  Actions:  $ACTIONS"
echo "  Setup:    $SETUP"
echo ""
echo "  Manifest: $MANIFEST"
echo "  Client env written: $CLIENT_ENV"
echo ""
echo "Build the client against this deploy:"
echo "  cd client && pnpm install && pnpm build --mode sepolia"
echo ""
echo "Or run a dev preview:"
echo "  cd client && pnpm install && pnpm dev --mode sepolia"
echo "============================================"
